set -g status-style fg="#654735",bg="#f9f5d7"
set -g status-left ""
set -g status-right "#(basename #{pane_current_path}) %H:%M %t"
set -g status-interval 5
set-option -g status-position bottom
set-window-option -g window-status-format "#[fg=#654735,bg=#f9f5d7] #W "
set-window-option -g window-status-current-format "#[fg=#f9f5d7,bg=#654735] #W "
set -g pane-border-style fg=#427b58
set -g pane-active-border-style bg="#f9f5d7",fg="#b57614"
